services:
    monapache3:
        image: maelgbrt/monapache3
        ports:
            - "${PORT_SITE}:80"
        environment:
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
    mariadb:
        image: mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${DB_NAME}
            - MARIADB_USER=${DB_USER}
            - MARIADB_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./bd_data:/var/lib/mysql
        ports:
            - "${PORT_DB}:3306"

    phpmyadmin:
        image: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - "${PORT_PMA}:80"